# Generated by Django 4.0.4 on 2022-05-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_apti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apti',
            name='Projeto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apti',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
