# Generated by Django 4.0.4 on 2022-05-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_apti_projeto_alter_apti_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('linkLusofona', models.URLField()),
                ('linkLinkedin', models.URLField()),
            ],
        ),
    ]
