# Generated by Django 4.0.4 on 2022-05-15 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='feedbackColega',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='linkCadeira',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tipo',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=500)),
                ('imagem', models.ImageField(upload_to=None)),
                ('linkCadeira', models.URLField()),
                ('linkGitHub', models.URLField()),
                ('linkYoutube', models.URLField()),
                ('tecnologias', models.CharField(max_length=100)),
                ('linkPortfolio', models.URLField(null=True)),
                ('competencias', models.ManyToManyField(to='portfolio.apti')),
                ('pessoa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.pessoa')),
            ],
        ),
    ]
