# Generated by Django 4.0.4 on 2022-05-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_blog_feedbackcolega_pessoa_linkcadeira_pessoa_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='linkCadeira',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='pessoa_id',
        ),
    ]
