# Generated by Django 4.0.4 on 2022-05-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_pessoa_linklinkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='linkLinkedin',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='linkLusofona',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tipo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
