# Generated by Django 4.0.4 on 2022-05-17 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_pessoa_linklinkedin_pessoa_linklusofona_pessoa_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('descricao', models.TextField()),
                ('linguagens', models.CharField(max_length=50)),
                ('docente_teorica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.pessoa')),
                ('docentes_praticas', models.ManyToManyField(related_name='praticas', to='portfolio.pessoa')),
                ('projetos', models.ManyToManyField(to='portfolio.projeto')),
            ],
        ),
    ]
