# Generated by Django 4.0.4 on 2022-05-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_cadeira'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='linguagens',
            field=models.CharField(max_length=30),
        ),
    ]
