# Generated by Django 4.0.4 on 2022-05-17 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_linguagem_alter_cadeira_linguagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='linguagens',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('alunos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.pessoa')),
            ],
        ),
    ]
