# Generated by Django 4.0.4 on 2022-05-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_cadeira_linguagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='curso',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cadeira',
            name='linguagens',
            field=models.CharField(default='', max_length=20),
        ),
    ]
