# Generated by Django 4.0.4 on 2022-05-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_cadeira_curso_remove_cadeira_linguagens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escolas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensino', models.CharField(max_length=50)),
                ('periodo', models.IntegerField()),
                ('local', models.CharField(max_length=150)),
                ('lototipo', models.ImageField(upload_to=None)),
            ],
        ),
    ]
