# Generated by Django 4.0.4 on 2022-05-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_escolas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escolas',
            old_name='lototipo',
            new_name='logotipo',
        ),
        migrations.AddField(
            model_name='escolas',
            name='curso',
            field=models.CharField(default='', max_length=50),
        ),
    ]
