# Generated by Django 4.0.4 on 2022-05-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_rename_lototipo_escolas_logotipo_escolas_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='ola',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='ano',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='nome',
            field=models.CharField(default='', max_length=20),
        ),
    ]
