# Generated by Django 4.0.4 on 2022-05-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_cadeira_ola_alter_cadeira_ano_alter_cadeira_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadeira',
            old_name='ola',
            new_name='ranking',
        ),
    ]
