# Generated by Django 4.0.4 on 2022-05-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_remove_curso_alunos_curso_alunos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='alunos',
            field=models.ManyToManyField(null=True, to='portfolio.pessoa'),
        ),
    ]
