# Generated by Django 4.0.4 on 2022-05-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_alter_curso_alunos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='alunos',
            field=models.ManyToManyField(blank=True, to='portfolio.pessoa'),
        ),
    ]
