# Generated by Django 4.0.4 on 2022-05-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_alter_curso_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='linkPortfolio',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='linkPortfolio',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
