# Generated by Django 4.0.4 on 2022-05-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_remove_projeto_linkportfolio_pessoa_linkportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='paticipantes',
            field=models.ManyToManyField(to='portfolio.pessoa'),
        ),
    ]
