# Generated by Django 4.0.4 on 2022-05-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_projeto_paticipantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='ano',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='linkGitHub',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='linkYoutube',
            field=models.URLField(blank=True),
        ),
    ]
