# Generated by Django 4.0.4 on 2022-05-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_cadeira_ects'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='semestre',
            field=models.CharField(default='', max_length=20),
        ),
    ]
