# Generated by Django 4.0.4 on 2022-05-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_cadeira_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('acronimo', models.CharField(max_length=50)),
                ('ano_criacao', models.CharField(max_length=50)),
                ('criador', models.CharField(max_length=50)),
                ('logotipo', models.ImageField(upload_to=None)),
                ('link_site_oficial', models.URLField()),
                ('descricao_caracteristicas', models.TextField()),
            ],
        ),
    ]
