# Generated by Django 4.0.4 on 2022-05-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_tecnologia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='tecnologias',
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnologias',
            field=models.ManyToManyField(to='portfolio.tecnologia'),
        ),
    ]
