# Generated by Django 4.0.4 on 2022-05-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_laboratorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('imagem', models.ImageField(upload_to=None)),
            ],
        ),
    ]
