# Generated by Django 4.0.4 on 2022-05-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologia',
            name='tipo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
