# Generated by Django 4.0.4 on 2022-05-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_tecnologia_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontuacaoQuizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pontuacao', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='noticia',
            name='texto',
            field=models.TextField(),
        ),
    ]
