# Generated by Django 4.0.4 on 2022-05-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_pontuacaoquizz_alter_noticia_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escolas',
            name='logotipo',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
