# Generated by Django 4.0.4 on 2022-05-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_alter_blog_imagem_alter_noticia_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologia',
            name='logotipo',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
