# Generated by Django 4.0.4 on 2022-05-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0035_alter_tecnologia_logotipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imagem',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.CreateModel(
            name='TrabalhoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('sumario', models.CharField(max_length=50)),
                ('resumo', models.CharField(max_length=500)),
                ('linkrelatorio', models.URLField()),
                ('linkgithub', models.URLField()),
                ('linkYoutube', models.URLField()),
                ('autor', models.ManyToManyField(related_name='autor', to='portfolio.pessoa')),
                ('orientador', models.ManyToManyField(related_name='orientador', to='portfolio.pessoa')),
            ],
        ),
    ]
