# Generated by Django 4.0.4 on 2022-05-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0036_alter_blog_imagem_trabalhofinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imagem',
            field=models.ImageField(upload_to='blogeiros/'),
        ),
    ]
