# Generated by Django 4.0.4 on 2022-05-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0038_alter_blog_imagem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Escolas',
            new_name='Formacao',
        ),
    ]
