# Generated by Django 4.0.4 on 2022-05-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0039_rename_escolas_formacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('topicos_abordados', models.CharField(max_length=300)),
                ('link_heroku', models.URLField()),
                ('imagem', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
    ]
