# Generated by Django 4.0.4 on 2022-05-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0041_delete_laboratorios_laboratorio_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao_1', models.CharField(max_length=30)),
                ('questao_2', models.IntegerField(default=0)),
                ('questao_3', models.IntegerField(default=0)),
                ('questao_4', models.CharField(max_length=70)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='PontuacaoQuizz',
        ),
    ]
