# Generated by Django 4.0.4 on 2022-05-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0042_quizz_delete_pontuacaoquizz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imagem',
            field=models.ImageField(blank=True, default='default.png', upload_to='media/'),
        ),
    ]
