# Generated by Django 4.0.4 on 2022-05-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0045_rename_disciplina_apti_disciplinas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnologia',
            name='criador',
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='criador',
            field=models.ManyToManyField(to='portfolio.pessoa'),
        ),
    ]
