# Generated by Django 4.0.4 on 2022-05-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0046_remove_tecnologia_criador_tecnologia_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='linkLinkedin',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='linkLusofona',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
