# Generated by Django 4.0.4 on 2022-05-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0048_alter_cadeira_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadeira',
            name='curso',
        ),
        migrations.AddField(
            model_name='cadeira',
            name='curso',
            field=models.ManyToManyField(to='portfolio.curso'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='projetos',
            field=models.ManyToManyField(blank=True, to='portfolio.projeto'),
        ),
    ]
