# Generated by Django 4.0.4 on 2022-05-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0049_remove_cadeira_curso_cadeira_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='imagem',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
