# Generated by Django 4.0.4 on 2022-05-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0050_cadeira_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='linguagens',
            field=models.ManyToManyField(blank=True, to='portfolio.linguagem'),
        ),
    ]
