# Generated by Django 4.0.4 on 2022-06-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0054_comenatario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalhofinal',
            name='sumario',
        ),
        migrations.AddField(
            model_name='cadeira',
            name='linkCadeira',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='trabalhofinal',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trabalhofinal',
            name='imagem',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='trabalhofinal',
            name='linkYoutube',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='trabalhofinal',
            name='linkgithub',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='trabalhofinal',
            name='linkrelatorio',
            field=models.URLField(blank=True),
        ),
    ]
