# Generated by Django 4.0.4 on 2022-06-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0056_trabalhofinal_deisi_delete_trabalhofinal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrabalhoFinal_deisi',
        ),
    ]
