# Generated by Django 4.0.4 on 2022-06-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0057_delete_trabalhofinal_deisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalho_Final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('descricao', models.TextField(blank=True, default='')),
                ('resumo', models.CharField(max_length=500)),
                ('linkrelatorio', models.URLField(blank=True)),
                ('linkgithub', models.URLField(blank=True)),
                ('linkYoutube', models.URLField(blank=True)),
                ('imagem', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('autor', models.ManyToManyField(related_name='autor', to='portfolio.pessoa')),
                ('orientador', models.ManyToManyField(related_name='orientador', to='portfolio.pessoa')),
            ],
        ),
    ]
