# Generated by Django 4.0.4 on 2022-06-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0058_trabalho_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalho_final',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='trabalho_final',
            name='resumo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
